apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mz3b9xe63-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mz3b9xe63-python 
  name: mz3b9xe63-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mz3b9xe63-python 
